# Google credentials and configuration
google_client_id:      YOUR_CLIENT_ID
google_client_secret:  YOUR_CLIENT_SECRET
google_project_id:     gotophoto 

# options are "mysql", "postgres", "mongodb", or "datastore"
gotophoto_backend: mysql

# configure CloudSQL for MySQL or PostgreSQL backend
cloudsql_connection_name: gotophoto:australia-southeast1:gotophoto
cloudsql_database_name: photo_db 
cloudsql_user: gotophoto_admin
cloudsql_password: CwRqyNfTJPfn5Tz
cloudsql_port: 3306

# configure Mongo backend
mongo_url: YOUR_MONGODB_URL
mongo_database: YOUR_MONGO_DATABASE
mongo_collection: YOUR_MONGO_COLLECTION
